# Generated by Django 5.1.4 on 2025-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='AttributeNames',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='attribute',
            new_name='attr',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
