# Generated by Django 5.1.4 on 2025-01-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_attribute_attributenames_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeNames',
            new_name='AttributeName',
        ),
    ]
