# Generated by Django 5.1.4 on 2025-01-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributename',
            options={'verbose_name': 'Attribute Name', 'verbose_name_plural': 'Attribute Names'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Attribute Value', 'verbose_name_plural': 'Attribute Values'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
    ]
