# Generated by Django 5.1.4 on 2025-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_long_desciption_product_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
