# Generated by Django 5.1.4 on 2025-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productvariation_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='discount_price',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
