# Generated by Django 5.1.4 on 2025-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_store_alter_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='store',
        ),
        migrations.AddField(
            model_name='seller',
            name='cnpj',
            field=models.CharField(default=124, max_length=14, unique=True, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='comercial_number',
            field=models.CharField(default=111, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_address',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_cep',
            field=models.CharField(default=12121145, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_city',
            field=models.CharField(default='arasra', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_complement',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_neighborhood',
            field=models.CharField(default='fsfs', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_number',
            field=models.CharField(default=12, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='store_state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='MG', max_length=2),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
