# Generated by Django 5.1.4 on 2025-01-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='complement',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
