# Generated by Django 5.1.4 on 2025-01-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_total_qty'),
        ('order', '0006_alter_order_status_alter_orderitem_variation_and_more'),
    ]

    operations = [
    ]
